package com.ssm.runoob.dao;

import com.ssm.runoob.model.Role;
import com.ssm.runoob.model.RolePrivilege;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insert(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int insertSelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    Role selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Role record);

    List<Role> findByQueryAndOrderBy(@Param("search") String search, @Param("order") String order, @Param("start") int start, @Param("length") int length);

    long count();

    long countByQuery(@Param("search") String search);

    int insertAssign(@Param("rps") List<RolePrivilege> rps);

    int removeRPAssignAllByRID(@Param("rid") Long rid);

    int removeURAssignAllByRID(@Param("rid") Long rid);

    List<Role> getAll();

    List<Role> getAllRolePrivilege();
}